name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'index.html'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
        uses: actions/checkout@v3
    - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './'  # Points to the folder containing index.html

